language: go
go:
- 1.11.x
script:
- env GO111MODULE=on go mod download
- env GO111MODULE=on go test -race ./...
notifications:
  email:
    on_success: never
    on_failure: always
before_deploy:
- env GO111MODULE=on GOOS=linux go build -o bin/phoval-linux cmd/main/main.go
- env GO111MODULE=on GOOS=darwin go build -o bin/phoval-mac cmd/main/main.go
- env GO111MODULE=on GOOS=windows go build -o bin/phoval.exe cmd/main/main.go
deploy:
  provider: releases
  api_key:
    secure: wJlQhgL3nZmYOsh4HYKYg5U2nqpXB1A3MO1A9aqHJWIuxrXFzPy/rIVPXVstNrgVeOSe75dO4czuZFw7g67v6FZh1btfxeVuPZUVlENrtUPrfnuA4QB9ReEo2idyCHKzaQHRdP+m2JMt3x6y0d7ckl1U4lYo0ucXKcv31t0wEGxodM6ccmWjrEaFQOd3eb1sNrg/AEQEhX9BR14i/ZW7/jietj8FkkIOsvZrHBk4x4s+qML/28xuwRGluMbIDqNhcXBkyWeBNN+eEHudyMVWHxzNxLGgP9GifqwtvzVlKy+srjeKY7uyq3xMPuJcLCUfzZ3Vb4gdkcvPqo4RQ1rijQRXAMY8XUhls2JKMm384mzXE1qWwSIjkB4thvXknPwZlRWnZNfjrG923kGJJWTN9pRf7ByHB/TXr2T0+N0Ma8fBdLpKJmfH+X8sLGL4V4cQfAIdrRL/I57SSFP9ig0bBcgInXImJRuQwUTj2c1o5FQ236xah/3HExvnEknBRvhUwrsI8LhuLyp4LPtEhfA83Nq18s9PO3HCUFcCpWuPi8TI3GqnCgKmF90/mop6cIiafjIzwcrs/SqQxddJB8QTEWy4labXY+VUT18ow8xxr3W9k1whSSiffXVBMsxCfkFD75tddkAqEKrYRYYjTXCSmOKtjed7RIx2oYFMYN9m1AU=
  on:
    repo: monteiro/phoval
    branch: master
